### ISSUE TITLE
Supervisord worker seems not working queeus

### ISSUE THREAD

**Issue by cswni** [jkaninda/laravel-php-fpm#48]
The section [supervisorctl] missing from supervisor.conf main file.

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

Previous sections able to start, stop supervisorctl but restarting container no persisting config

**Comment by jkaninda** [comment]
I just tested, everything works fine

**Comment by jkaninda** [comment]
You can add it in /var/www/html/conf/worker/supervisor.conf, it'll imported automatical

**Comment by jkaninda** [comment]
You can add it in /var/www/html/conf/worker/supervisor.conf.
It'll imported automatical
