### ISSUE TITLE
Opcache

### ISSUE THREAD

**Issue by asiraky** [jkaninda/laravel-php-fpm#55]
Yo FYI you should really consider install opcache ` docker-php-ext-install opcache` and setting up a ini file https://gist.github.com/rohankhudedev/1a9c0a3c7fb375f295f9fc11aeb116fe. You will get some serious performance improvements.

**Comment by jkaninda** [comment]
Opcache has been installed, thank you!

**Comment by jkaninda** [comment]
Integrated
