### ISSUE TITLE
More info about file config?

### ISSUE THREAD

**Issue by ssheduardo** [jkaninda/laravel-php-fpm#59]
Can you give more information on how to use this?

![image](https://github.com/jkaninda/laravel-php-fpm/assets/1160138/55c3fa8a-0628-4dc0-9af2-34e3d9e798f5)

Great job, by the way.
I want to be able to adapt my docker configuration to your images.

**Comment by jkaninda** [comment]
In case you want to execute and maintain a task or process with supervisor,
an example with Apache Kafka, when you want to maintain a consumer's process

[Example:](https://github.com/jkaninda/laravel-php-fpm#example)

```conf
[program:kafkaconsume-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan kafka:consumer
autostart=true
autorestart=true
numprocs=1
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/kafka.log
```
