### ISSUE TITLE
There is no existing directory at "/var/www/storage/logs" and it could not be created: Permission denied

### ISSUE THREAD

**Issue by EnzoDosSantos** [jkaninda/laravel-php-fpm#68]
Hello, I tried to solve the storage permissions error with the steps in the README, it didn't work, I also tried doing it from a Dockerfile, it didn't give me a solution either, any ideas? I would also like to know how to disable APP_DEBUG

![image](https://github.com/jkaninda/laravel-php-fpm/assets/101943986/9b964e98-0d63-4285-ae77-47a650299de1)

**Comment by EnzoDosSantos** [comment]
these are the permissions inside the container

![image](https://github.com/jkaninda/laravel-php-fpm/assets/101943986/10c8360d-f158-46c3-befe-040068ecf1a7)

I have also disabled the debug, but it still appears

![image](https://github.com/jkaninda/laravel-php-fpm/assets/101943986/1956db4e-e60f-4d88-8c03-2e6a7d500068)

![image](https://github.com/jkaninda/laravel-php-fpm/assets/101943986/c313f641-13c9-4ef6-8f2c-a0141773678d)

**Comment by jkaninda** [comment]
You can do this:  chown -R www-data:www-data /var/www/html, and debug is applied from your .env file, please check it in your .env file.
You can also apply it directly from the environment in your docker-compose.yaml file and it will override the existing environment in .env
```yaml
environment:
       - APP_DEBUG=false
```
